### PR TITLE
Fix vagrant matching in 'get_ip'

### LINKED ISSUE #1703: The get_ip method should match on any vagrant-backed hypervisor
The method currently has a match on `vagrant` but this misses `vagrant_libvirt` (and anything else that is added in the future)

### PR DESCRIPTION
**Pull request by trevor-vaughan**
Update the match in `get_ip` to match on any hypervisor matching
`vagrant`.

Fixes #1703

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]

File: lib/beaker/host/unix/exec.rb [hunk 1]
```diff
@@ -138,7 +138,9 @@ def get_ip
     if self['platform'].include?('solaris') || self['platform'].include?('osx')
       execute("ifconfig -a inet| awk '/broadcast/ {print $2}' | cut -d/ -f1 | head -1").strip
     else
-      execute("ip a | awk '/global/{print$2}' | cut -d/ -f1 | #{self['hypervisor'] == 'vagrant' ? 'tail' : 'head'} -1").strip
+
+      pipe_cmd = "#{self['hypervisor']}".include?('vagrant') ? 'tail' : 'head'
```
Comment (ekohl) [inline lib/beaker/host/unix/exec.rb:142]: Why is the string interpolation needed? Is it in case it's nil? Isn't it better to write:
`pipe_cmd = self['hypervisor']&.include?('vagrant') ? 'tail' : 'head'`
